"""empty message

Revision ID: 2ffc1ab4f33b
Revises: a93fe36fe77f
Create Date: 2025-02-10 20:31:18.956115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffc1ab4f33b'
down_revision = 'a93fe36fe77f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clausule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_controls',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_standards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clausule_comment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clausule_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clausule_id'], ['clausule.id'], name='fk_ClausuleComment_clausule_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_standard_clausule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=True),
    sa.Column('control_id', sa.UUID(), nullable=True),
    sa.Column('standard_id', sa.UUID(), nullable=True),
    sa.Column('clausule_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clausule_id'], ['clausule.id'], name='fk_DomainStandardClausule_clausule_id'),
    sa.ForeignKeyConstraint(['control_id'], ['security_controls.id'], name='fk_DomainStandardClausule_securityControls_id'),
    sa.ForeignKeyConstraint(['domain_id'], ['security_domains.id'], name='fk_DomainStandardClausule_securityDomains_id'),
    sa.ForeignKeyConstraint(['standard_id'], ['security_standards.id'], name='fk_DomainStandardClausule_securityStandards_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('clausules')
    op.drop_table('standards')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('standards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clausules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('domain_standard_clausule')
    op.drop_table('clausule_comment')
    op.drop_table('security_standards')
    op.drop_table('security_domains')
    op.drop_table('security_controls')
    op.drop_table('clausule')
    # ### end Alembic commands ###
