"""empty message

Revision ID: 7fde8ee2d36c
Revises: 8abd4d8ec6a3
Create Date: 2025-05-19 21:00:27.763631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fde8ee2d36c'
down_revision = '8abd4d8ec6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clausule_comment')
    with op.batch_alter_table('clausule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('standard_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(length=50), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_DomainStandardClausule_securityStandards_id', 'security_standards', ['standard_id'], ['id'])

    with op.batch_alter_table('domain_standard_clausule', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('domain_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('control_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('standard_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('clausule_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.drop_column('start_date')
        batch_op.drop_column('end_date')

    with op.batch_alter_table('security_controls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.String(length=50), nullable=True))

    with op.batch_alter_table('security_domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.String(length=50), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('security_standards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.String(length=50), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('security_standards', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('version')

    with op.batch_alter_table('security_domains', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('version')

    with op.batch_alter_table('security_controls', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('domain_standard_clausule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DATETIME(), nullable=True))
        batch_op.alter_column('clausule_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('standard_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('control_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('domain_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('clausule', schema=None) as batch_op:
        batch_op.drop_constraint('fk_DomainStandardClausule_securityStandards_id', type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('version')
        batch_op.drop_column('standard_id')
        batch_op.drop_column('title')

    op.create_table('clausule_comment',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('clausule_id', sa.NUMERIC(), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['clausule_id'], ['clausule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
